In [10]:
import pandas as pd

df = pd.read_csv("tablice_trygonometryczne.csv", sep=";", decimal=",")
df.head()

,a,sin,cos,tg,ctg,x,x2,x3,x+r,1/x
0,0.00,0.000000,1.00000,0.000000,#DZIEL/0!,0.00,0.0000,0.000000,0.012293,#DZIEL/0!
1,0.01,0.010000,0.99995,0.010000,"99,99333318",0.05,0.0025,0.000125,0.069529,20
2,0.02,0.019999,0.99980,0.020003,"49,98666542",0.10,0.0100,0.001000,0.127612,10
3,0.03,0.029996,0.99955,0.030009,"33,31332913",0.15,0.0225,0.003375,0.173646,"6,666666667"
4,0.04,0.039989,0.99920,0.040021,"24,97332337",0.20,0.0400,0.008000,0.213493,5

In [15]:
new_df = df.dropna()
df.dropna(inplace=True)
df

,a,sin,cos,tg,ctg,x,x2,x3,x+r,1/x
0,0.00,0.000000,1.000000,0.000000,#DZIEL/0!,0.00,0.0000,0.000000,0.012293,#DZIEL/0!
1,0.01,0.010000,0.999950,0.010000,"99,99333318",0.05,0.0025,0.000125,0.069529,20
2,0.02,0.019999,0.999800,0.020003,"49,98666542",0.10,0.0100,0.001000,0.127612,10
3,0.03,0.029996,0.999550,0.030009,"33,31332913",0.15,0.0225,0.003375,0.173646,"6,666666667"
4,0.04,0.039989,0.999200,0.040021,"24,97332337",0.20,0.0400,0.008000,0.213493,5
...,...,...,...,...,...,...,...,...,...,...
625,6.25,-0.033179,0.999449,-0.033197,"-30,11168857",31.25,976.5625,30517.578130,31.294299,"0,032"
626,6.26,-0.023183,0.999731,-0.023189,"-43,11530466",31.30,979.6900,30664.297000,31.334282,"0,031948882"
627,6.27,-0.013185,0.999913,-0.013186,"-75,83320435",31.35,982.8225,30811.485380,31.395995,"0,031897927"
628,6.28,-0.003185,0.999995,-0.003185,"-313,9393407",31.40,985.9600,30959.144000,31.446864,"0,031847134"
629,6.29,0.006815,0.999977,0.006815,"146,7372141",31.45,989.1025,31107.273630,31.488128,"0,031796502"